trap SIGINT to suppress noisy stack traces
GoogleCloudPlatform/market-data-transcoder pull request #113
Opened 2023-03-07 01:34 UTC by salsferrazza

Control-C'ing out of a transcoder process run in the foreground exits with a very noisy stack trace that inhibits immediate diagnostics of the last few messages. This CL traps SIGINT and exists more gracefully. It also provides the basic entry point for #13 and #111.

2023-03-07 02:51 UTC, mservidio submitted a review, later dismissed

2023-03-07 17:05 UTC, t8dogg reviewed
Useful and comprehensible, LGTM

2023-03-07 17:06 UTC, t8dogg approved these changes

2023-03-07 19:26 UTC, t8dogg approved these changes

2023-03-07 19:50 UTC, mservidio commented
@salsferrazza needs some linting clean up, I touched up a couple of the issues

2023-03-07 20:07 UTC, t8dogg approved these changes
The linting LGTM @mservidio

2023-03-10 02:39 UTC, mservidio requested changes

2023-03-10 02:39 UTC, mservidio commented on transcoder/message/MessageParser.py
> +    def summary(self):
Should probably rename to print_summary or log_summary?

2023-03-10 02:39 UTC, mservidio commented on transcoder/main.py
> +    global message_parser
The linter doesn't like using global. It appears that signal can be wired up to instances: https://stackoverflow.com/questions/34786524/signal-handler-inside-a-class

2023-03-10 03:01 UTC, mservidio commented
One other thought, the logic in main.py will only be a feature add for cli usage, but not library usage. Moving this into the MessageParser instance may be more beneficial.

2023-03-10 03:06 UTC, mservidio commented
I'm going to mark this WIP, and raise a separate PR trapping from MessageParser.

2023-03-10 03:48 UTC, mservidio commented
@salsferrazza re-factored a little, take a look...

2023-03-10 15:52 UTC, mservidio approved these changes

2023-03-10 15:53 UTC, merged